name: Release

on:
  push:
    branches:
      - main

jobs:
  main:
    name: NPM Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Using Node v14 because npm > 6.x.x is provided in that
      - name: Use Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          CI: true

      # Building the package is handled within the prepare npm phase
      - name: Build package
        run: npm run build:lib

      - name: Release new version to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
